### ISSUE TITLE
Variation graph from large number of individuals

### ISSUE THREAD

**Issue by priyambial123** [SandraLouise/SVJedi-graph#1]
Hello,

Can I build the variation graph with combined vcf file from a large number of individuals and use this graph to identify the genotype in another independent sample?

Should the vcf file and the fastq file be from the same individual?

Thank you

Priya

**Comment by SandraLouise** [comment]
Hello Priya,

You can build the variation graph with any vcf file as long as all the SVs described in this vcf were called on the reference genome that will be used to construct the same variation graph. So the vcf file can contain calls from multiple individuals. Please note that only SV types mentionned in the README (currently DEL, INS, INV, BND) will be represented in the graph.

Then you can use this variation graph to genotype any individual for which you have a fastq, it does not have to be an individual that was used to produce the vcf.

There are two points to be aware of:
1- For now SVJedi-graph can only handle one-individual genotyping (fastq from only one individual). If you want to genotype multiple individuals, you will need to run SVJedi-graph on each independant fastq.
2- As the reads are mapped to the graph using minigraph and without base-level alignment, SVJedi-graph may have trouble genotyping individuals the more they are divergent to the reference genome used.

Thank you for your interest in SVJedi-graph

Sandra
